import Head from 'next/head';
import { GetStaticProps } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { Product, ProductsPackage } from '../types';
import indexStyles from '../styles/index.module.css';

export const getStaticProps: GetStaticProps = async () => {
	const res = await fetch('https://dummyjson.com/products');
	const results: ProductsPackage = await res.json();

	return {
		props: {
			products: results.products,
		},
	};
};

function Home({ products }: ProductsPackage) {
	return (
		<div className={indexStyles.products}>
			<Head>
				<title>NextJS with TS Practice</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Electronics and more!</h1>
			<h4>Links below each image will open a new page/tab with more details</h4>
			{products &&
				products.map((product: Product) => {
					return (
						<div key={product.id}>
							<Image
								src={product.images && product.images[0]}
								alt={product.description || 'image not available'}
								width={'200'}
								height={'200'}
							/>
							<Link
								href={`/products/${product.id}`}
								target={'_blank'}
								className={indexStyles['products-link']}
							>
								<h3>{product.title}</h3>
							</Link>
						</div>
					);
				})}
		</div>
	);
}

export default Home;
